### ISSUE TITLE
add endpoint DELETE /playlist/[playlistId]/record

### ISSUE THREAD

**Issue by Insire** [Insire/MonstercatNet#6]
[See](https://github.com/defvs/connect-v2-docs/wiki/Playlists#removing-a-record-from-a-playlist-delete-playlistplaylistidrecord)

- should include unit tests for validating the request in memory
- should include integration/live test for executing the request against the actual monstercat api

**Comment by karimelazzouni** [comment]
Hello @Insire , I tried running the tests locally (throw VS and through running `build.ps1` but 6 tests are always failing with a `401 Unauthorized access`, probably because I am not signed in. Am I missing something? Is there a prerequisite for running those tests locally? Or are they expected to fail?

**Comment by Insire** [comment]
Hi. Yes there is. Some tests test "gold only" features. So if you dont have an account with a gold membership setup, those will always fail.

You can setup the account here: 
![grafik](https://user-images.githubusercontent.com/11455827/94225960-add44100-fef6-11ea-87c7-c90b507cbb03.png)

Which expects some json, which looks like this

```json
{
  "ApiCredentials": {
    "email": "",
    "password": ""
  }
}
```

**Comment by Insire** [comment]
I will be taking this on this weekend.
